create schema H2_SCHOOL_DEMO_1;

create table H2_SCHOOL_DEMO_1.ACTORS
(
    AID CHARACTER VARYING(4) not null primary key,
    FULL_NAME CHARACTER VARYING(55) default NULL unique ,
    BORN      DATE                  default NULL,
    CONTACT   CHARACTER VARYING(10) default NULL
);


INSERT INTO H2_SCHOOL_DEMO_1.ACTORS (AID, FULL_NAME, BORN, CONTACT) VALUES ('A003', 'Aaron Taylor-Johnson', '1990-06-13', '0396235321');
INSERT INTO H2_SCHOOL_DEMO_1.ACTORS (AID, FULL_NAME, BORN, CONTACT) VALUES ('A005', 'Dwayne Johnson', '1972-07-21', '0316235122');
INSERT INTO H2_SCHOOL_DEMO_1.ACTORS (AID, FULL_NAME, BORN, CONTACT) VALUES ('A004', 'Jason Statham', '1967-11-26', '0716235107');
INSERT INTO H2_SCHOOL_DEMO_1.ACTORS (AID, FULL_NAME, BORN, CONTACT) VALUES ('A006', 'Liam Neeson', '1952-06-07', '0165062620');
INSERT INTO H2_SCHOOL_DEMO_1.ACTORS (AID, FULL_NAME, BORN, CONTACT) VALUES ('A001', 'Julia Rehwald', '1995-09-19', '0326562322');

create table H2_SCHOOL_DEMO_1.MOVIES
(
    MID  CHARACTER VARYING(4)  not null  primary key,
    TITLE      CHARACTER VARYING(55) default null,
    CATEGORIES CHARACTER VARYING(60) default null,
    RATE       NUMERIC(2, 1)         default null,
    `YEAR`       DATE                  default null
);
INSERT INTO H2_SCHOOL_DEMO_1.MOVIES (MID, TITLE, CATEGORIES, RATE, `YEAR`) VALUES ('M001', 'Fallout', 'Action,Adventure,Drama', 8.2, '2024-04-11');
INSERT INTO H2_SCHOOL_DEMO_1.MOVIES (MID, TITLE, CATEGORIES, RATE, `YEAR`) VALUES ('M002', 'Kick-Ass 2', 'Action,Comedy,Crime', 6.8, '2018-01-18');
INSERT INTO H2_SCHOOL_DEMO_1.MOVIES (MID, TITLE, CATEGORIES, RATE, `YEAR`) VALUES ('M003', 'Nocturnal Animals', 'Drama,Thriller', 7.5, '2016-12-15');
INSERT INTO H2_SCHOOL_DEMO_1.MOVIES (MID, TITLE, CATEGORIES, RATE, `YEAR`) VALUES ('M004', 'The Interview', 'Action,Comedy', 6.2, '2014-12-20');
INSERT INTO H2_SCHOOL_DEMO_1.MOVIES (MID, TITLE, CATEGORIES, RATE, `YEAR`) VALUES ('M005', 'Jurassic World: Rebirth', 'Action,Comady', 7.1, '2020-11-02');
INSERT INTO H2_SCHOOL_DEMO_1.MOVIES (MID, TITLE, CATEGORIES, RATE, `YEAR`) VALUES ('M009', 'Taken 3', 'Action', 7.8, '2015-06-01');


create table H2_SCHOOL_DEMO_1.ACTORS_MOVIES
(
    AID CHARACTER VARYING(4) not null,
    MID CHARACTER VARYING(4) not null,
    primary key (AID, MID),
    constraint FK_ACTORS_ACTORS_MOVIES
        foreign key (AID) references H2_SCHOOL_DEMO_1.ACTORS,
    constraint FK_MOVIES_ACTORS_MOVIES
        foreign key (MID) references H2_SCHOOL_DEMO_1.MOVIES
);

INSERT INTO H2_SCHOOL_DEMO_1.ACTORS_MOVIES (AID, MID) VALUES ('A003', 'M002');
INSERT INTO H2_SCHOOL_DEMO_1.ACTORS_MOVIES (AID, MID) VALUES ('A003', 'M003');
INSERT INTO H2_SCHOOL_DEMO_1.ACTORS_MOVIES (AID, MID) VALUES ('A006', 'M009');

