spring.application.name=spring-boot-crud-h2-many-to-many-for-angular-with-primeng
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
# set log of jdbc if you wanna see what statement is executing
logging.level.org.springframework.jdbc.core=trace
# this defines a base URL prefix for the entire application. All endpoints within the application will be accessible under this prefix.
server.servlet.context-path=/api



############ (New) Three ways config properties file i know ############
#### Note!  *** 3 ways have to run on cmd
#### Note!  2,3 you have to set permission on your role as your system
#### Note!  when you build jar file as mvn clean install you have to skip test as "mvn clean install -Dmaven.test.skip=tru"




#### 1.import another properties outside project (external)
#spring.config.import=optional:file:B:/env/h2-many-to-many/info.properties
#spring.datasource.driver-class-name=${jdbc.driver}
#spring.datasource.url=${jdbc.url}
#spring.datasource.username=${jdbc.username}
#spring.datasource.password=${jdbc.password}




#### 2.import another properties outside project (external) (open *** cmd (terminal not working) then run) when run mvn
#### mvn spring-boot:run -Dspring-boot.run.arguments="--spring.config.import=optional:file:B:/env/h2-many-to-many/info.properties"
#### java -jar target/spring-boot-crud-h2-many-to-many-0.0.1-SNAPSHOT.jar --spring.config.import=optional:file:B:/env/h2-many-to-many/info.properties
#spring.datasource.driver-class-name=${jdbc.driver}
#spring.datasource.url=${jdbc.url}
#spring.datasource.username=${jdbc.username}
#spring.datasource.password=${jdbc.password}




#### 3. import properties for config file when run mvn (open *** cmd (terminal not working) then run)
#### mvn spring-boot:run -Dspring-boot.run.arguments="--spring.config.import=optional:file:B:/env/h2-many-to-many/info_config.properties"
#### java -jar target/spring-boot-crud-h2-many-to-many-0.0.1-SNAPSHOT.jar --spring.config.import=optional:file:B:/env/h2-many-to-many/info_config.properties




# for access h2 server on web browser # spring.h2.console.enabled=true # spring.h2.console.path=/h2-console
