spring.application.name=spring-boot-crud-h2-many-to-many-for-angular-with-primeng
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
spring.config.import=classpath:info/db.properties
