spring.application.name=spring-boot-crud-h2-many-to-many-for-angular-with-primeng
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
# set log of jdbc if you wanna see what statement is executing
logging.level.org.springframework.jdbc.core=trace
spring.config.import=classpath:info/db.properties
# h2 config
spring.datasource.driver-class-name=${jdbc.driver}
spring.datasource.url=${jdbc.url}
spring.datasource.username=${jdbc.username}
spring.datasource.password=${jdbc.password}
# for access h2 server on web browser
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# this defines a base URL prefix for the entire application. All endpoints within the application will be accessible under this prefix.
server.servlet.context-path=/api